[package]
name = "geyser-grpc-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
yellowstone-grpc-client = "1.11.0"
yellowstone-grpc-proto = "1.11.0"

solana-sdk = "~1.16.17"

async-stream = "0.3.5"
tokio = { version = "1.28.2" , features = ["full"] }
futures = "0.3.28"
anyhow = "1.0.70"
log = "0.4.17"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
prometheus = "0.13.3"
itertools = "0.10.5"
base64 = "0.21.5"
bincode = "1.3.3"

#[dev-dependencies]
#solana-test-validator = "~1.16.17"
