[package]
name = "geyser-grpc-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
yellowstone-grpc-client = "1.11.0"
yellowstone-grpc-proto = "1.11.0"

solana-sdk = "~1.16.3"

async-trait = "0.1.68"
async-stream = "0.3.5"
tokio = { version = "1.32" , features = ["full"] }
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
bincode = "1.3.3"
bs58 = "0.4.0"
base64 = "0.21.0"
thiserror = "1.0.40"
futures = "0.3.28"
bytes = "1.4.0"
anyhow = "1.0.70"
log = "0.4.17"
dashmap = "5.4.0"
const_env = "0.1.2"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
chrono = "0.4.24"
prometheus = "0.13.3"
lazy_static = "1.4.0"
async-channel = "1.8.0"
itertools = "0.10.5"
