[package]
name = "geyser-grpc-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
yellowstone-grpc-client = "1.11.0"
yellowstone-grpc-proto = "1.11.0"

solana-sdk = "~1.16.17"

url = "2.5.0"
async-stream = "0.3.5"
tokio = { version = "1.28" , features = ["rt"] }
futures = "0.3.28"
merge-streams = "0.1.2"
anyhow = "1.0.70"
log = "0.4.17"
tracing = "0.1.37"
itertools = "0.10.5"
derive_more = "0.99.17"

base64 = "0.21.5"
bincode = "1.3.3"

[dev-dependencies]
tracing-subscriber = "0.3.16"
